const Map<String, String> appStringsEn = {
  'appName': 'Goal Countdown',
  'appTagline': 'Count down to what matters most',
  'splashLoading': 'Loading your goals...',
  'onboardingTitle1': 'Track your goals',
  'onboardingDesc1': 'Add countdowns to your most important life events — exams, weddings, birthdays, trips and more.',
  'onboardingTitle2': 'Never miss a moment',
  'onboardingDesc2': 'Real-time countdowns show days, hours, minutes and seconds until each goal. Stay focused.',
  'onboardingTitle3': 'Earn stars & customize',
  'onboardingDesc3': 'Collect stars daily, buy packs via Google Play, unlock themes, backgrounds and premium features.',
  'getStarted': 'Get Started',
  'skip': 'Skip',
  'next': 'Next',
  'navGoals': 'Goals',
  'navShop': 'Shop',
  'navSettings': 'Settings',
  'goalsTitle': 'My Goals',
  'goalsEmpty': 'No goals yet',
  'goalsEmptyHint': 'Tap + to add your first goal countdown.',
  'addGoal': 'Add Goal',
  'editGoal': 'Edit Goal',
  'deleteGoal': 'Delete Goal',
  'deleteGoalConfirm': 'Delete this goal?',
  'deleteGoalDesc': 'This action cannot be undone.',
  'goalTitle': 'Goal title',
  'goalTitleHint': 'e.g. University Exam',
  'goalDescription': 'Description (optional)',
  'goalDescriptionHint': 'Add a note...',
  'goalDate': 'Target date',
  'goalCategory': 'Category',
  'goalSaved': 'Goal saved!',
  'goalDeleted': 'Goal deleted',
  'goalLimitReached': 'Goal limit reached — unlock unlimited in Shop',
  'goalLimitInfo': '{current}/{max} goals (free plan)',
  'cat_exam': 'Exam',
  'cat_wedding': 'Wedding',
  'cat_birthday': 'Birthday',
  'cat_travel': 'Travel',
  'cat_deadline': 'Deadline',
  'cat_other': 'Other',
  'daysLeft': '{days} days',
  'dayLeft': '1 day',
  'hoursLeft': '{hours}h {minutes}m',
  'today': 'Today!',
  'goalPast': 'Goal passed',
  'goalPastDays': '{days} days ago',
  'countdown': 'Countdown',
  'days': 'Days',
  'hours': 'Hours',
  'minutes': 'Min',
  'seconds': 'Sec',
  'share': 'Share',
  'edit': 'Edit',
  'delete': 'Delete',
  'sharedVia': 'Goal Countdown',
  'shareGoalText': '{title}\n{days} days to go!\n\n— shared via Goal Countdown',
  'adPlaceholder': 'Ad space — Remove ads in Shop',
  'removeAds': 'Remove',
  'save': 'Save',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'active': 'Active',
  'shopBrowse': 'Browse items',
  'shopTitle': 'Shop',
  'shopSubtitle': 'Earn stars or buy more to unlock',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuCards': 'Backgrounds',
  'shopMenuSkins': 'Card skins',
  'shopMenuFeatures': 'Features',
  'shopEmptyCategory': 'No items in this category',
  'yourWallet': 'Your star wallet',
  'coinsLabel': 'stars',
  'earnCoins': 'Earn stars free',
  'earnStepDaily': '• Daily login: +10 stars',
  'earnStepAddGoal': 'Add a goal',
  'earnStepAddGoalDesc': '• Add goal: +10 stars (max 3/day)',
  'earnStepShare': 'Share a goal',
  'earnStepShareDesc': '• Share: +5 stars (max 3/day)',
  'earnStepBuy': '• Buy star packs via Google Play',
  'claimDailyButton': 'Claim daily +10',
  'dailyRewardDone': 'Daily reward claimed',
  'buyCoins': 'Buy stars',
  'buyCoinsDesc': 'Purchase star packs to unlock items faster.',
  'yourCoins': 'You have {count} stars',
  'coinPack': 'Pack {num}',
  'coinAmount': '{count} stars',
  'earnCoinsHint': 'Or earn stars for free in the wallet section above.',
  'billingDisabled': 'Google Billing disabled — redeem with stars only',
  'billingUnavailable': 'Google Play Billing is not available',
  'productsNotFound': 'Products not found. Check Play Console setup.',
  'processingPurchase': 'Processing purchase...',
  'openingBilling': 'Opening Google Play...',
  'configNetworkError': 'Network error. Using cached config.',
  'configTimeout': 'Request timed out. Using cached config.',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed',
  'insufficientCoins': 'Not enough stars',
  'alreadyOwned': 'Already owned',
  'owned': 'Owned',
  'apply': 'Apply',
  'applied': 'Applied!',
  'resetDefault': 'Default',
  'resetToDefault': 'Reset to default',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Hide banner ads permanently.',
  'removeAdsIap': 'Buy via Google Play',
  'removeAdsUnlocked': 'Ads removed!',
  'buyWithGooglePlay': 'Buy now',
  'shopThemeSunset': 'Sunset theme',
  'shopThemeSunsetDesc': 'Warm coral tones.',
  'shopThemeMidnight': 'Midnight theme',
  'shopThemeMidnightDesc': 'Deep blue night vibes.',
  'shopThemeTropical': 'Forest theme',
  'shopThemeTropicalDesc': 'Fresh green energy.',
  'shopThemeSakura': 'Sakura theme',
  'shopThemeSakuraDesc': 'Soft pink blossom.',
  'shopBgSunrise': 'Sunrise glow',
  'shopBgSunriseDesc': 'Warm orange gradient.',
  'shopBgOcean': 'Ocean waves',
  'shopBgOceanDesc': 'Blue wave gradient.',
  'shopBgAurora': 'Aurora borealis',
  'shopBgAuroraDesc': 'Purple-green aurora.',
  'shopBgGalaxy': 'Galaxy night',
  'shopBgGalaxyDesc': 'Deep space gradient.',
  'shopSkinGlass': 'Glass card',
  'shopSkinGlassDesc': 'Frosted glass goal card.',
  'shopSkinMinimal': 'Minimal card',
  'shopSkinMinimalDesc': 'Clean sharp edges.',
  'shopSkinElegant': 'Elegant card',
  'shopSkinElegantDesc': 'Rounded premium style.',
  'shopFeatUnlimitedGoals': 'Unlimited goals',
  'shopFeatUnlimitedGoalsDesc': 'Add unlimited goals (free: 5).',
  'shopFeatReminders': 'Goal reminders',
  'shopFeatRemindersDesc': 'Get notified before your goals.',
  'shopFeatExportGoals': 'Export goals',
  'shopFeatExportGoalsDesc': 'Export goals as JSON.',
  'shopFeatWidget': 'Widget styles',
  'shopFeatWidgetDesc': 'Premium home screen widget themes.',
  'shopFeatCustomIcons': 'Custom icons',
  'shopFeatCustomIconsDesc': 'Unlock 4 extra goal categories: Achievement, Health, Finance, Personal.',
  'cat_achievement': 'Achievement',
  'cat_health': 'Health',
  'cat_finance': 'Finance',
  'cat_personal': 'Personal',
  'shopFeatNoWatermark': 'No watermark',
  'shopFeatNoWatermarkDesc': 'Share goals without app branding.',
  'coinsAdded': '+{amount} stars added to wallet!',
  'dailyRewardClaimed': '+{amount} stars — daily reward!',
  'addGoalRewardEarned': '+{amount} stars — goal added!',
  'shareRewardEarned': '+{amount} stars — goal shared!',
  'coinRewardSub': 'Wallet balance: {balance} stars',
  'settingsTitle': 'Settings',
  'language': 'Language',
  'english': 'English',
  'vietnamese': 'Vietnamese',
  'darkMode': 'Dark mode',
  'privacyPolicy': 'Privacy policy',
  'version': 'Version',
  'about': 'About',
  'aboutDesc': 'Goal Countdown helps you track time to your most important events. All goals are stored locally on your device.',
  'activeTheme': 'Active theme',
  'activeBackground': 'Active background',
  'activeSkin': 'Active card skin',
  'widgetInfo': 'Home screen widget',
  'widgetInfoDesc': 'Long-press home screen → Widgets → Goal Countdown',
  'widgetStylesLocked': 'Unlock widget styles in Shop',
  'appearance': 'Appearance',
  'other': 'Other',
  'exportSuccess': 'Goals copied to clipboard',
  'openShop': 'Open Shop',
  'openShopDesc': 'Themes, features & buy stars',
  'copyright': '© 2026 Goal Countdown',
  'activeCustomization': 'Customization',
  'privacyPolicyTitle': 'Privacy Policy',
  'privacyPolicyBody': 'Goal Countdown stores all goals locally on your device. We do not collect or upload your personal data.\n\nInternet is used only to fetch IAP configuration (R211.json) and process Google Play purchases.\n\nPurchases are handled by Google Play Billing. We do not store payment card information.\n\nContact: support@goalcountdown.app',
};
